### ISSUE TITLE
Team sync on two-month development plan

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#149]
Hey all - it has been several months since we last met, and the EBP stack has evolved considerably. I also have a little bit more bandwidth now as I am climbing out of my early-parenthood hole.

I think it would be helpful to have a team sync to discuss where we are in the grant lifecycle, and to share our respective goals / priorities for the next two-or-so months. That way we can coordinate development efforts a bit. (this will also let us ensure that we aren't asking too much of @chrisjsewell who now has a 60/40 split with EPFL).

It is going to be really hard to find a time that works across AUS/CA/EUR, but I am happy to try and have a synchronous meeting if you all wish. I'm also happy to have a structured GitHub issue where we discuss asynchronously (in which case I'll probably send out some prompts that we can fill out, and then we can all converge on a plan after this).

What do you all think? 

# Combined list from below

## Themes

- [x] Improve the left ToC bar: have it appear from the side on mobile, and have collapsible sections (https://github.com/executablebooks/sphinx-book-theme/issues/112)
- [x] Improve the customisability of certain aspects, including using CSS custom variables
- [x] Improve the modularity of both SCSS and Jinja templates (possibly taking inspiration from https://github.com/jupyter/nbconvert/pull/1056)
  - See https://github.com/executablebooks/sphinx-book-theme/pull/237
- [ ] Custom title/landing page (https://github.com/executablebooks/sphinx-book-theme/issues/162)
- [ ] Port features from other themes? (quantecon-book-theme: resize text, back-to-top button)
- [x] Finalizing v0.1 of the sphinx-book-theme. See the [milestone for `v0.1` to guide us forward there](https://github.com/executablebooks/sphinx-book-theme/milestone/1).
- [ ] [theme prototype + theme modularity]: more `modular` elements to themes to enable `theme features` as mentioned above.

## Execution

- [ ] making cache the default, and making some improvements to jupyter-cache, and perhaps integrating it better into jupyter-book (e.g. easy cli options for pre/re-executing notebooks outside of the actual build process)
- [ ] More consistent project/notebook/cell level configuration options in myst-nb (including https://github.com/executablebooks/jupyter-book/issues/666)
- [ ] skipping cell executions https://github.com/executablebooks/jupyter-book/issues/833
- [ ] some improvements on the rendering side like kernel-agnostic glue functionality.

## Latex improvements

- [x] [LaTeX theme support] Continue work on building LaTeX theme support to see if we can introduce enough customization without having to support a full LaTeX writer/translator. 
- [x] [LaTeX] Build Support for `jupyter-cache` outputs for the generic PDF writer to enable outputs in LaTeX
- [ ] [LaTeX Single Page] Build better individual pages using the generic LaTeX writer for possible `download` pdf options in theme. https://github.com/executablebooks/jupyter-book/issues/904
- [x] [Notebook as Output] Find the best technical solution for thinking of `notebooks` as output. This would be useful to support downloadable notebooks with options to update relative links to objects with links to web location etc.https://github.com/executablebooks/jupyter-book/issues/886

## MyST Markdown and HTML improvments

- [x] Improvment/generalisation of `:::` block syntax (https://github.com/executablebooks/MyST-Parser/issues/259#issuecomment-701663046)
- [ ] I think getting mdformat to work with MyST-Markdown would be a really nice feature.
- [ ] Markdown format for doctrings
- [x] Improving MyST Markdown in HTML/JS
  - see https://github.com/executablebooks/markdown-it-myst
- [x] Finalize an early release of [sphinx-tomyst](https://github.com/executablebooks/sphinx-tomyst) 

## Examples / outreach

- [x] More examples of built books. Now that we have a number of folks building books with Jupyter Book, I think we should find a way to highlight and show them off as an example gallery or something to give folks inspiration.
  - http://gallery.jupyterbook.org/
- [ ] Write a short paper so that others can cite the EBP stack (see #150)
- [x] Migrating https://python-programming.quantecon.org to be powered by `jupyter-book`

## Extra Jupyter Book features

- [x] Integrate sphinx-multitoc-numbering in jupyter-book?
- [ ] Support for blogging (https://github.com/executablebooks/jupyter-book/issues/900)

**Comment by chrisjsewell** [comment]
Sure ting, I'm just gonna start copying what I wrote on Slack here...

To my mind, for EBP/jupyter-book, 2 of the main things that need focus are the theme and the _toc.yml  (if you look in jupyter-book you'll see plenty of issues labelled for both), which hopefully we are moving in the right direction with.

For the sphinx-book-theme:

- Improve the left ToC bar: have it appear from the side on mobile, and have collapsible sections (https://github.com/executablebooks/sphinx-book-theme/issues/112)
- Improve the customisability of certain aspects, including using CSS custom variables
- Improve the modularity of both SCSS and Jinja templates (possibly taking inspiration from https://github.com/jupyter/nbconvert/pull/1056)
- Custom title/landing page (https://github.com/executablebooks/sphinx-book-theme/issues/162)
- Port features from other themes? (quantecon-book-theme: resize text, back-to-top button)

For the toc:

- Integrate sphinx-parttoc-numbering in jupyter-book?

Then I'd like to spend a little time re-appraising the notebook execution:

- making cache the default, and making some improvements to jupyter-cache, and perhaps integrating it better into jupyter-book (e.g. easy cli options for pre/re-executing notebooks outside of the actual build process)
- More consistent project/notebook/cell level configuration options in myst-nb (including https://github.com/executablebooks/jupyter-book/issues/666)
- skipping cell executions https://github.com/executablebooks/jupyter-book/issues/833
- some improvements on the rendering side like kernel-agnostic glue functionality.

Additional things (if time):

- Support for blogging (https://github.com/executablebooks/jupyter-book/issues/900)
- I think getting mdformat to work with MyST-Markdown would be a really nice feature.
- Markdown format for doctrings

**Comment by akhmerov** [comment]
If the meeting is synchronous, I'd really appreciate a possibility to listen in. I'd also like to suggest making a spec for cell nodes, and potentially moving it to jupyter-sphinx. Or at the very least fixing the spec, so that CSS & thebe play along nicely.

**Comment by mmcky** [comment]
Thanks @chrisjsewell that is a great summary from Slack. Some status updates from `ANU`:

- We are in the business end of migrating https://python-programming.quantecon.org to be powered by `jupyter-book` and using that migration to get [sphinx-tomyst](https://github.com/executablebooks/sphinx-tomyst) for bulk conversion of projects to `alpha` for release through PyPI. We will continue to make improvements to [sphinx-tomyst](https://github.com/executablebooks/sphinx-tomyst) as we migrate https://python.quantecon.org and https://python-advanced.quantecon.org
- [theme prototype + theme modularity] We have done some work on a prototype theme `quantecon-book-theme`. It is currently standalone for prototyping purposes but would like to iterate on features and help work towards building more `modular` elements to themes to enable `theme features` as mentioned above. @chrisjsewell -- @AakashGfude would like to help work on this with you. 

Our medium term development focus is:

- [LaTeX] Build Support for `jupyter-cache` outputs for the generic PDF writer to enable outputs in LaTeX
- [LaTeX theme support] Continue work on building LaTeX theme support to see if we can introduce enough customization without having to support a full LaTeX writer/translator. 
- [LaTeX Single Page] Build better individual pages using the generic LaTeX writer for possible `download` pdf options in theme. https://github.com/executablebooks/jupyter-book/issues/904
- [Notebook as Output] Find the best technical solution for thinking of `notebooks` as output. This would be useful to support downloadable notebooks with options to update relative links to objects with links to web location etc.https://github.com/executablebooks/jupyter-book/issues/886

**Comment by choldgraf** [comment]
Thanks all for your thoughts - here is my own take on what to prioritize

Note that right now most of my time is going towards 👶 and towards setting up contracts / funding / etc. I actually don't have much time for EBP development right now but will put in what time I can to help push forward on these issues.

# General point

I think that at this point we should be shifting more of our time into **debugging, answering issues, and implementing features that users ask for**. Don't forget that we [have a feature leaderboard](https://executablebooks.org/en/latest/feature-vote.html), and in general we should follow the lead of what our users ask of us when we have the cycles.

More generally, I'd like to see everybody associated with the EBP project to be responding to issues, questions, and spot-checking bugs and improvements across the broader EBP stack (in particular the core pieces, like myst-parser, myst-nb, sphinx-book-theme, and jupyter-book). As the userbase grows, we need to make sure we all pay attention to these repositories. This will be important both in making sure users feel supported and comfortable using the tools, but also because it's a great signal to decide what features are most important to work on next or fix.

# Specific things to work on

- **Improving MyST Markdown in HTML/JS** - I'm in the process of working out details for a sub-contract to [Iooxa](https://iooxa.dev/) to do some web development on our javascript implementations of myst markdown and libraries that we'll be able to integrate into web-based editors. [Here is a sample SOW for this contract](https://docs.google.com/document/d/1BrJ3_USeE5OkL5Ia7S8eRBhULiq4RmIh_2PZY432KWk/edit) (it's only accessible to those under the grant who are on this thread). Would love feedback from folks there.
- **Finalizing v0.1 of the sphinx-book-theme**. The Sphinx Book Theme has a number of improvements to design and implementation that would make it much better. I've created a [milestone for `v0.1` to guide us forward there](https://github.com/executablebooks/sphinx-book-theme/milestone/1). Feel free to comment on any of those issues or make progress on them.
- **More examples of built books**. Now that we have a number of folks building books with Jupyter Book, I think we should find a way to highlight and show them off as an example gallery or something to give folks inspiration.
- **Write a short paper** so that others can cite the EBP stack (see #150)

Other than that, I agree w/ all of @chrisjsewell 's points. Note that I decided to play around with re-writing [my own website/blog in Sphinx](https://predictablynoisy.com/blog/) and it worked pretty well. So we may be close-ish to blogging with Jupyter Book if we wish (or perhaps that should be a different project like `jupyter-blog`? Worth discussing!

**Comment by AakashGfude** [comment]
Thank you guys for the summary. and @mmcky on a briefing about what we are prioritizing at the moment. I like the approach of @choldgraf to focus on user-centric issues atm. As per the discussion with @mmcky, we plan to devote at least one or two days equivalent of time per week on *debugging, answering issues, and implementing features* until all the migration tasks are taken care of after which planning to devote more time.

**Comment by jstac** [comment]
> I think that at this point we should be shifting more of our time into debugging, answering issues, and implementing features that users ask for. Don't forget that we have a feature leaderboard, and in general we should follow the lead of what our users ask of us when we have the cycles.

I agree.  I have selfish requests (vim support for myst editing :grimacing: ) but I'd rather we are guided by the community.  The only thing I would add is that we made promises to our funding organization and fulfilling those promises needs a positive weighting too.  For example, continued emphasis on high quality hardcopy.

(That said, I suspect our funding organization would prefer us to be guided by our user base rather than blindly ticking off metrics.)

I encourage @AakashGfude and @mmcky to engage a bit more with users in real time. :grin:   

I'm very strongly in favor of a gallery of interesting jupyter books.  Love that idea.

**Comment by mmcky** [comment]
> `Improving MyST Markdown in HTML/JS` 

This is an exciting project. If I understand correctly this is about getting full support natively for `myst` notebooks to be rendered in the browser. So I guess my only comment is the first two components `markdown-it-myst` and `Standard Web components` are the highest priority parts of the work package? Just thinking you might want to scope a staged delivery plan as part of the `SOW` -- to bring focus on the core elements. But not sure how formal or informal you need to make the `sow`

**Comment by choldgraf** [comment]
Hey all - I have collected many of the responses that people gave in this thread and created a single list above:

https://github.com/executablebooks/meta/issues/149#issue-709031207

I'll try to re-visit that list over time as we make progress. It seems like we have a ways to go for many of the items that are there.

**Comment by choldgraf** [comment]
Hey all - it's now been about two months. I went through the original list and ticked a few boxes that I think we are making progress on, or have been addressed. Can @mmcky + @AakashGfude comment on the Latex-focused items up there, and @chrisjsewell note progress on the deliverables he's got across the few categories there? If there are things blocking folks then I wanna make sure that we get them un-blocked.

**Comment by chrisjsewell** [comment]
> @chrisjsewell note progress on the deliverables he's got across the few categories there?

FYI I've been concentrating on finishing some AiiDA deliverables for the last few weeks (as with everything, they take took longer than expected lol).
But I'm going to concentrate on EBP now for the next week (and probably all this month) so I will write a bit of an update on all of this at the end of the week then 😬

**Comment by choldgraf** [comment]
Sounds great 👍 LMK if others on the team can help with something. And good luck with finishing up the AiiDA push

**Comment by chrisjsewell** [comment]
Yep will do cheers; always feels a bit like I'm "robbing Peter to pay Paul" whether I'm focussing on AiiDA or EBP lol, but I think by the end of the year I can just about have pleased everyone 😬 

FYI, been doing a fair bit of work on automating setup/testing of python environments /  jupyter kernels / jupyter apps on different platforms (docker, cloud VMs, Linux).
So if anyone has questions about that kind of thing, I might have the answer 😉,
and also I want to think about how that can be applied to EBP (like use of containerised notebook executions)

- https://github.com/marvel-nccr/ansible-role-aiida
- https://quantum-mobile.readthedocs.io
- https://www.materialscloud.org/work/aiidalab

**Comment by choldgraf** [comment]
nice! maybe @alex-treebeard would be interested in that as I know he's been working on various CI/CD+notebooks things lately: https://github.com/executablebooks/meta/discussions/183

**Comment by chrisjsewell** [comment]
Indeed and, as mentioned there, I also have my own notebook CI package: https://pytest-notebook.readthedocs.io

**Comment by mmcky** [comment]
Thanks @choldgraf some updates. 

> [Notebook as Output] Find the best technical solution for thinking of notebooks as output.

To get download notebooks supported we have put together [sphinx-tojupyter](https://github.com/quantecon/sphinx-tojupyter) which is essentially a migration of the writers that used to power `jupinx`. It builds notebooks from `sphinx.ast`. It builds notebooks that contain only basic markdown (but isn't spec compliant at the moment), but this does mean we can build notebooks without `myst` (until javascript support is available) and could be useful to support some `slide` features being requested by the `quantecon` author community. It is currently in the `quantecon` organisation but can move to `ebp` if others think it would be useful. An [example notebook](https://python-programming.quantecon.org/_notebooks/matplotlib.ipynb) and we use these notebooks to support `binder` (which we have swapped to using from colab). 

@AakashGfude can you update on the other LaTeX items from [jupyterbook-latex](https://github.com/executablebooks/jupyterbook-latex). Thanks!

**Comment by AakashGfude** [comment]
Some LaTex developments in [jupyterbook-latex](https://github.com/executablebooks/jupyterbook-latex) : 

1)  **TOC** : - 

Parts, chapters, sections are being handled in TOC now. With continuous numbering between Parts. Children files (specified with `section` key) in chapters are handled for LaTex by inlining them with the top-level section of the parent file,i.e,  The children file titles are being considered as h2 headers in the parent file. 
`url` key in TOC is ignored in the final PDF output for now, which is what sphinx does as well because of many complications arising from it as outlined in this comment https://github.com/sphinx-doc/sphinx/issues/701#issuecomment-289689442 . 
`tableofContents` node is ignored at the  moment, as it includes the files itself in latex instead of the links (because we are using toctree node). Plan to handle it by converting it to reference nodes for LaTeX.

2) **Master doc**

Master doc page is treated as a front matter page. As an introduction to the book. It does not appear in the TOC. All the pages section and subsections are converted to bolded text of varying sizes, based on the level of the section.

3)  **Code cell tags**

 `hide-input`, `hide-output`, `hide-cell` are handled by hiding them in the output PDF.

4)  **Others**

Changing table of contents title to `Contents` . Using `myst_amsmath_enable` flag to render math.  Using a theme file called `jupyterBook.cls` to load packages and writing latex commands. Handling `gif` and `png` image formats.
