### ISSUE TITLE
Start monthly EBP team meetings

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#379]
The team of folks working on ExecutableBooks repositories is starting to diversify a bit, and given that we're already distributed around the world, I think it would be helpful for us to have a monthly team meeting to have some face time and coordinate a bit.

I propose that we start having **monthly Executable Books team meetings**. Here are a few proposals:

# When would they happen?

Once a month (e.g., first Tuesday of the month).

For times, we have a couple of options:

- Pick a time that works for everybody on the team. This is going to be really hard with people split across AUS, USA, UK. I think our best bet would be something like 7 or 8am Australia time. But this would put @chrisjsewell at midnight UK time :-/ 
- Alternate times to switch between Pacific-friendly and Americas-friendly. One meeting would start at 8 or 9am California time, the next meeting would start at 1 or 2am California time, and we'd alternate.

In case it helps, here's a little interactive viz of some of our team members time zones: https://whena.re/ebp-core-team

# Who would join?

Anybody is welcome to join, and @executablebooks/ebpteam members (e.g., anybody with commit rights to an EBP repository) are highly encouraged to join.

# What would the format be?

I'd propose a lightweight combination of **short announcements, reports, and shout-outs**, as well as **discussion points**. The goal of the meeting is **not** to just report what we've been up to, it is to interact with one another via discussion (either towards work-related stuff, or just to catch up). So we'd keep the "report what you've been up to" topics to be relatively short (2-3 minutes each).

We could use structure an agenda with this HackMD, and copy/paste the notes into the `meta/` repository at the end of each meeting:

https://hackmd.io/THymMOAmSICp8rJdB6_Z1w

# Where would it happen?

We'd set up a zoom room on a recurring calendar invite, and put this link on the executablebooks.org website. Anybody would have access to this zoom room if they wished.

# Tasks

- [x] Set up infrastructure and docs for our meetings
- [x] Have our first meeting
- [x] Decide if anything needs to be updated / changed
  - [x] https://github.com/executablebooks/meta/issues/419
  - [x] Make sure that the "team meetings" page is accessible to all
  - [x] Include both an AUS + Cali time for the next meetings to make sure the day is clear for all
  - [x] Tell twitter about our latest team meeting
- [x] Close this when we think we are in steady-state

**Comment by jstac** [comment]
Thanks for organzing @choldgraf .  7am would work for me, which is 11pm for @chrisjsewell according to the whena diagram --- not sure if that's too late?

**Comment by mmcky** [comment]
7am can work for me too. Thanks @choldgraf -- I think this is a great idea.

**Comment by AakashGfude** [comment]
I would love to join as well. Thanks, @choldgraf.

**Comment by damianavila** [comment]
I think this is a great idea!
About the time zone issue, we can figure it out... it seems there is a center of gravity around 7 am AUS time for now.
Although alternating times sounds reasonable to me as well.

**Comment by choldgraf** [comment]
Hey all - I've added a PR with a proposed agenda and calendar to use in coordinating meetings. Would love to know what people think about this structure, and the suggestion that we start off on Thursday, July 1st!

https://github.com/executablebooks/meta/pull/404

**Comment by jstac** [comment]
Looking forward to it :+1:

**Comment by choldgraf** [comment]
I've just opened up an issue to track our first team meeting! #414 

We can decide if this format works for folks and iterate here, or close this issue if we are happy w/ it.

**Comment by akhmerov** [comment]
I have a question/point of feedback. I've read through the notes (sadly had to miss the meeting itself), and many items appear interesting, but also imply that there was more to the discussion than the notes contain. Is there a way to get more information? Did you consider keeping and/or publishing the video recordings or audio transcripts?

**Comment by choldgraf** [comment]
We haven't discussed video recordings, we might look into this but these kinds of things always require extra time and we are already pretty thin on time as it is. I think as a start we should see how far we can get with keeping and posting notes. (this is similar to how JupyterHub does things, e.g.: https://jupyterhub-team-compass.readthedocs.io/en/latest/monthly-meeting/2021-06-17.html)

There wasn't actually a lot extra that wasn't in the notes, a lot of this meeting was going over a backlog of pre-existing items, so we didn't dig into a ton of future-facing items. I suspect that future meetings will have more time for discussion in general.

**Comment by choldgraf** [comment]
Closing this one as I've got the calendar updated so it's accessible now. We can use future team meetings to iterate on the structure / content!
