### ISSUE TITLE
Team Meeting - July

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#414]
Hello @executablebooks/ebpteam! This is an issue to track the next Executable Books team meeting! Here's some relevant information:

- **Date**: 2021-07-01 at 07:00 Sydney Time (or [your timezone](https://arewemeetingyet.com/Sydney/2021-07-01/07:00/EBP-Team-Meeting)).
- **Agenda+Video links**: [HackMD](https://hackmd.io/THymMOAmSICp8rJdB6_Z1w?edit)

If you'd like to discuss something at the meeting, please add an item to the agenda!

# Tasks

- [x] Update dates and make sure HackMD information is correct
- [x] Add discussion items
- [x] Have the meeting
- [x] Turn any follow-ups into issues/comments/etc
    - https://github.com/executablebooks/sphinx-external-toc/issues/45
    - https://github.com/executablebooks/meta/issues/417
- [x] Copy the meeting notes to the docs: https://github.com/executablebooks/meta/pull/418
- [x] Remove notes from HackMD to prep for next meeting
- [x] Done 🎉

**Comment by mmcky** [comment]
thanks @choldgraf will start updating `HackMD`

**Comment by choldgraf** [comment]
Reminder to the @executablebooks/ebpteam that we'll have our first meeting **tomorrow** (see the link above for the specific time/date/agenda)

**Comment by choldgraf** [comment]
I've checked off all the boxes at the top, so closing this one! :-0
