### ISSUE TITLE
Team Meeting - August 04/05

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#442]
Hello @executablebooks/ebpteam! This is an issue to track the next Executable Books team meeting! Here's some relevant information:

- **Date**: 2021-08-05 at 7AM Sydney Time> (or [your timezone](https://arewemeetingyet.com/Sydney/2021-08-05/07:00/EBP-Team-Meeting)).
- **Agenda+Video links**: [HackMD](https://hackmd.io/THymMOAmSICp8rJdB6_Z1w?edit)

If you'd like to discuss something at the meeting, please add an item to the agenda!

# Tasks

- [x] Update dates and make sure HackMD information is correct
- [x] Add discussion items
- [x] Have the meeting
- [x] Turn any follow-ups into issues/comments/etc
- [x] Copy the meeting notes to the docs
- [x] Remove notes from HackMD to prep for next meeting
- [x] Done 🎉

**Comment by choldgraf** [comment]
Note that **I am going to miss this meeting**. That said, I suggest that folks discuss the recent "Activity Boards" proposal here: #441 

Beyond that, I think a good use of time would be to coordinate and brainstorm some major efforts to focus on next (I remember in the last meeting @chrisjsewell suggested we take a look at the "feature voting" board... I think that's a great idea)

**Comment by chrisjsewell** [comment]
> Is somebody else from the @executablebooks/ebpteam able to run the meeting in my absense?

Yeh happy to take over (or happy to reschedule if you did want to be there?)

**Comment by choldgraf** [comment]
Thanks! I think we should just keep this meeting on a regular schedule so that it's at a predictable time for everybody. But I'm happy to follow up in threads asynchronously afterward if there are discussion points.

**Comment by mmcky** [comment]
thanks @chrisjsewell look forward to catching up tomorrow

**Comment by chrisjsewell** [comment]
https://epfl.zoom.us/j/64133342828
