### ISSUE TITLE
Implement the governance proposal described in https://github.com/executablebooks/meta/pull/843

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#846]
### Context

We have a governance proposal described in this PR:

- https://github.com/executablebooks/meta/pull/843

If merged, then the next step will be to implement those pieces. This is an issue to keep track of the steps we need to take to implement the ideas there:

- [ ] Create a `team-compass/` repository
	- [ ] Add the governance and code of conduct docs to it (from the PR)
	- [ ] Look at our `meta/` repository and decide if / what should exist there as well if it would be non-controversial
	- [ ] Create a `steering-council` and `core-team` group in our github org
	- [ ] Implement whatever changes we need to make according to the policy that is defined there
- [ ] Create the `myst-specification` repository
	- [ ] Rename `myst-spec` to `myst-specification`
	- [ ] Figure out and implement what needs to be done to make that repo a Source of Truth
- [ ] Create the `myst-enhancement-proposals` repository
	- [ ] Rename `myst-eps` to `myst-enhancement-proposals`
	- [ ] Update the documentation there with the process described in the PR above
	- [ ] Cross-link our Team Compass to this repository

After this, the Steering Council can begin iterating on formal policy for the organization.

**Comment by rowanc1** [comment]
This is great. :)
Just a note on the MyST spec repo rename, if we rename the repo we should likely rename the subdomain and the NPM package (and deprecate the current package). I guess this might be coming out of my comment about naming things with clear/obvious names, if so, I think words like spec and demo are pretty clear (looks like spec is in the Oxford dictionary and the first hit on Google, for example). However, if we decide on the rename, I can help move the other things over.

**Comment by choldgraf** [comment]
I was only following the comments about fully spelling out the names - if `spec` is clear enough, we can just stick with that.

**Comment by rowanc1** [comment]
That sounds great. :)

**Comment by choldgraf** [comment]
OK I've merged in the Team Compass first PR, so this now exists 🎉 https://compass.executablebooks.org

I've scoped out an issue to do some information transfer between them:

- https://github.com/executablebooks/meta/issues/857

Can somebody on the @executablebooks/core-team volunteer to make the necessary changes to `myst-enhancement-proposals` so that it begins to resemble the policy defined in the team-compass?

Here's a start: https://compass.executablebooks.org/en/latest/meps.html

We can then move that content out of the team compass when it's ready to go.
